import React, { useContext } from "react";
import AppContext from "../context/AppContext";
import {
  abra,
  abra1,
  aerodactylMega,
  aerodactylMega1,
  aerodactyl,
  aerodactyl1,
  alakazamF,
  alakazamMega,
  alakazamMega1,
  alakazam,
  alakazam1,
  arbok,
  arbok1,
  arcanine,
  arcanine1,
  articuno,
  articuno1,
  beedrillMega,
  beedrillMega1,
  beedrill,
  beedrill1,
  bellsprout,
  bellsprout1,
  blastoiseMega,
  blastoiseMega1,
  blastoise,
  blastoise1,
  bulbasaur,
  bulbasaur1,
  butterfreeF,
  butterfreeF1,
  butterfree,
  butterfree1,
  caterpie,
  caterpie1,
  chansey,
  chansey1,
  charizardMegax,
  charizardMegax1,
  charizardMegay,
  charizardMegay1,
  charizard,
  charizard1,
  charmander,
  charmander1,
  charmeleon,
  charmeleon1,
  clefable,
  clefable1,
  clefairy,
  clefairy1,
  cloyster,
  cloyster1,
  cubone,
  cubone1,
  dewgong,
  dewgong1,
  diglettAlola,
  diglettAlola1,
  diglett,
  diglett1,
  ditto,
  ditto1,
  dodrioF,
  dodrioF1,
  dodrio,
  dodrio1,
  doduoF,
  doduoF1,
  doduo,
  doduo1,
  dragonair,
  dragonair1,
  dragonite,
  dragonite1,
  dratini,
  dratini1,
  drowzee,
  drowzee1,
  dugtrioAlola,
  dugtrioAlola1,
  dugtrio,
  dugtrio1,
  eevee,
  eevee1,
  ekans,
  ekans1,
  electabuzz,
  electabuzz1,
  electrode,
  electrode1,
  exeggcute,
  exeggcute1,
  exeggutorAlola,
  exeggutorAlola1,
  exeggutor,
  exeggutor1,
  farfetchd,
  farfetchd1,
  fearow,
  fearow1,
  flareon,
  flareon1,
  gastly,
  gastly1,
  gengarMega,
  gengarMega1,
  gengar,
  gengar1,
  geodudeAlola,
  geodudeAlola1,
  geodude,
  geodude1,
  gloomF,
  gloomF1,
  gloom,
  gloom1,
  golbatF,
  golbatF1,
  golbat,
  golbat1,
  goldeenF,
  goldeenF1,
  goldeen,
  goldeen1,
  golduck,
  golduck1,
  golemAlola,
  golemAlola1,
  golem,
  golem1,
  gravelerAlola,
  gravelerAlola1,
  graveler,
  graveler1,
  grimerAlola,
  grimerAlola1,
  grimer,
  grimer1,
  growlithe,
  growlithe1,
  gyaradosF,
  gyaradosF1,
  gyaradosMega,
  gyaradosMega1,
  gyarados,
  gyarados1,
  haunter,
  haunter1,
  hitmonchan,
  hitmonchan1,
  hitmonlee,
  hitmonlee1,
  horsea,
  horsea1,
  hypnoF,
  hypnoF1,
  hypno,
  hypno1,
  ivysaur,
  ivysaur1,
  jigglypuff,
  jigglypuff1,
  jigglypuF,
  jigglypuF1,
  jolteon,
  jolteon1,
  jynx,
  jynx1,
  kabuto,
  kabuto1,
  kabutops,
  kabutops1,
  kadabraF,
  kadabraF1,
  kadabra,
  kadabra1,
  kakuna,
  kakuna1,
  kangaskhanMega,
  kangaskhanMega1,
  kangaskhan,
  kangaskhan1,
  kingler,
  kingler1,
  koffing,
  koffing1,
  krabby,
  krabby1,
  lapras,
  lapras1,
  lickitung,
  lickitung1,
  machamp,
  machamp1,
  machoke,
  machoke1,
  machop,
  machop1,
  magikarpF,
  magikarp,
  magikarp1,
  magmar,
  magmar1,
  magnemite,
  magnemite1,
  magneton,
  magneton1,
  mankey,
  mankey1,
  marowakAlola,
  marowakAlola1,
  marowakTotem,
  marowakTotem1,
  marowak,
  marowak1,
  meowthAlola,
  meowthAlola1,
  meowth,
  meowth1,
  metapod,
  metapod1,
  mew,
  mew1,
  mewtwoMegax,
  mewtwoMegax1,
  mewtwoMegay,
  mewtwoMegay1,
  mewtwo,
  mewtwo1,
  moltres,
  moltres1,
  mrMime,
  mr_Mime,
  mr0_Mime,
  mr1_Mime,
  mukAlola,
  mukAlola1,
  muk,
  muk1,
  nidoking,
  nidoking1,
  nidoqueen,
  nidoqueen1,
  nidoran_f,
  nidoran_f1,
  nidoran_m,
  nidoran_m1,
  nidorina,
  nidorina1,
  nidorino,
  nidorino1,
  ninetalesAlola,
  ninetalesAlola1,
  ninetales,
  ninetales1,
  oddish,
  oddish1,
  omanyte,
  omanyte1,
  omastar,
  omastar1,
  onix,
  onix1,
  paras,
  paras1,
  parasect,
  parasect1,
  persianAlola,
  persianAlola1,
  persian,
  persian1,
  pidgeot,
  pidgeot1,
  pidgeotto,
  pidgeotto1,
  pidgey,
  pidgey1,
  pikachu_alolacap,
  pikachu_belle,
  pikachu_belle1,
  pikachu_cosplay,
  pikachu_cosplay1,
  pikachuF,
  pikachuF1,
  pikachu_hoenncap,
  pikachu_kaloscap,
  pikachu_kantocap,
  pikachu_libre,
  pikachu_partnercap,
  pikachu_phd,
  pikachu_phd1,
  pikachu_popstar,
  pikachu_popstar1,
  pikachu_rockstar,
  pikachu_rockstar1,
  pikachu_sinnohcap,
  pikachu_unovacap,
  pikachu,
  pikachu1,
  pinsirMega,
  pinsirMega1,
  pinsir,
  pinsir1,
  poliwag,
  poliwag1,
  poliwhirl,
  poliwhirl1,
  poliwrath,
  poliwrath1,
  ponyta,
  ponyta1,
  porygon,
  porygon1,
  primeape,
  primeape1,
  psyduck,
  psyduck1,
  raichuAlola,
  raichuAlola1,
  raichuF,
  raichuF1,
  raichu,
  raichu1,
  rapidash,
  rapidash1,
  raticateAlola,
  raticateAlola1,
  raticateF,
  raticateF1,
  raticateTotem,
  raticateTotem1,
  raticate,
  raticate1,
  rattataAlola,
  rattataAlola1,
  rattataF,
  rattataF1,
  rattata,
  rattata1,
  rhydonF,
  rhydon,
  rhydon1,
  rhyhornF,
  rhyhornF1,
  rhyhorn,
  rhyhorn1,
  sandshrewAlola,
  sandshrewAlola1,
  sandshrew,
  sandshrew1,
  sandslashAlola,
  sandslashAlola1,
  sandslash,
  sandslash1,
  scytherF,
  scyther,
  scyther1,
  seadra,
  seadra1,
  seakingF,
  seakingF1,
  seaking,
  seaking1,
  seel,
  seel1,
  shellder,
  shellder1,
  slowbroMega,
  slowbroMega1,
  slowbro,
  slowbro1,
  slowpoke,
  slowpoke1,
  snorlax,
  snorlax1,
  spearow,
  spearow1,
  squirtle,
  squirtle1,
  starmie,
  starmie1,
  staryu,
  staryu1,
  tangela,
  tangela1,
  tauros,
  tauros1,
  tentacool,
  tentacool1,
  tentacruel,
  tentacruel1,
  vaporeon,
  vaporeon1,
  venomoth,
  venomoth1,
  venonat,
  venonat1,
  venusaurF,
  venusaurF1,
  venusaurMega,
  venusaurMega1,
  venusaur,
  venusaur1,
  victreebel,
  victreebel1,
  vileplumeF,
  vileplumeF1,
  vileplume,
  vileplume1,
  voltorb,
  voltorb1,
  vulpixAlola,
  vulpixAlola1,
  vulpix,
  vulpix1,
  wartortle,
  wartortle1,
  weedle,
  weedle1,
  weepinbell,
  weepinbell1,
  weezing,
  weezing1,
  wigglytuff,
  wigglytuff1,
  wigglytuF,
  wigglytuF1,
  zapdos,
  zapdos1,
  zubatF,
  zubatF1,
  zubat,
  zubat1,
} from "../assets/pokedexGen1";

const pokemonAssetArr = [
  { id: "abra", pokemon: abra },
  { id: "abra1", pokemon: abra1 },
  { id: "aerodactylMega", pokemon: aerodactylMega },
  { id: "aerodactylMega1", pokemon: aerodactylMega1 },
  { id: "aerodactyl", pokemon: aerodactyl },
  { id: "aerodactyl1", pokemon: aerodactyl1 },
  { id: "alakazamF", pokemon: alakazamF },
  { id: "alakazamMega", pokemon: alakazamMega },
  { id: "alakazamMega1", pokemon: alakazamMega1 },
  { id: "alakazam", pokemon: alakazam },
  { id: "alakazam1", pokemon: alakazam1 },
  { id: "arbok", pokemon: arbok },
  { id: "arbok1", pokemon: arbok1 },
  { id: "arcanine", pokemon: arcanine },
  { id: "arcanine1", pokemon: arcanine1 },
  { id: "articuno", pokemon: articuno },
  { id: "articuno1", pokemon: articuno1 },
  { id: "beedrillMega", pokemon: beedrillMega },
  { id: "beedrillMega1", pokemon: beedrillMega1 },
  { id: "beedrill", pokemon: beedrill },
  { id: "beedrill1", pokemon: beedrill1 },
  { id: "bellsprout", pokemon: bellsprout },
  { id: "bellsprout1", pokemon: bellsprout1 },
  { id: "blastoiseMega", pokemon: blastoiseMega },
  { id: "blastoiseMega1", pokemon: blastoiseMega1 },
  { id: "blastoise", pokemon: blastoise },
  { id: "blastoise1", pokemon: blastoise1 },
  { id: "bulbasaur", pokemon: bulbasaur },
  { id: "bulbasaur1", pokemon: bulbasaur1 },
  { id: "butterfreeF", pokemon: butterfreeF },
  { id: "butterfreeF1", pokemon: butterfreeF1 },
  { id: "butterfree", pokemon: butterfree },
  { id: "butterfree1", pokemon: butterfree1 },
  { id: "caterpie", pokemon: caterpie },
  { id: "caterpie1", pokemon: caterpie1 },
  { id: "chansey", pokemon: chansey },
  { id: "chansey1", pokemon: chansey1 },
  { id: "charizardMegax", pokemon: charizardMegax },
  { id: "charizardMegax1", pokemon: charizardMegax1 },
  { id: "charizardMegay", pokemon: charizardMegay },
  { id: "charizardMegay1", pokemon: charizardMegay1 },
  { id: "charizard", pokemon: charizard },
  { id: "charizard1", pokemon: charizard1 },
  { id: "charmander", pokemon: charmander },
  { id: "charmander1", pokemon: charmander1 },
  { id: "charmeleon", pokemon: charmeleon },
  { id: "charmeleon1", pokemon: charmeleon1 },
  { id: "clefable", pokemon: clefable },
  { id: "clefable1", pokemon: clefable1 },
  { id: "clefairy", pokemon: clefairy },
  { id: "clefairy1", pokemon: clefairy1 },
  { id: "cloyster", pokemon: cloyster },
  { id: "cloyster1", pokemon: cloyster1 },
  { id: "cubone", pokemon: cubone },
  { id: "cubone1", pokemon: cubone1 },
  { id: "dewgong", pokemon: dewgong },
  { id: "dewgong1", pokemon: dewgong1 },
  { id: "diglettAlola", pokemon: diglettAlola },
  { id: "diglettAlola1", pokemon: diglettAlola1 },
  { id: "diglett", pokemon: diglett },
  { id: "diglett1", pokemon: diglett1 },
  { id: "ditto", pokemon: ditto },
  { id: "ditto1", pokemon: ditto1 },
  { id: "dodrioF", pokemon: dodrioF },
  { id: "dodrioF1", pokemon: dodrioF1 },
  { id: "dodrio", pokemon: dodrio },
  { id: "dodrio1", pokemon: dodrio1 },
  { id: "doduoF", pokemon: doduoF },
  { id: "doduoF1", pokemon: doduoF1 },
  { id: "doduo", pokemon: doduo },
  { id: "doduo1", pokemon: doduo1 },
  { id: "dragonair", pokemon: dragonair },
  { id: "dragonair1", pokemon: dragonair1 },
  { id: "dragonite", pokemon: dragonite },
  { id: "dragonite1", pokemon: dragonite1 },
  { id: "dratini", pokemon: dratini },
  { id: "dratini1", pokemon: dratini1 },
  { id: "drowzee", pokemon: drowzee },
  { id: "drowzee1", pokemon: drowzee1 },
  { id: "dugtrioAlola", pokemon: dugtrioAlola },
  { id: "dugtrioAlola1", pokemon: dugtrioAlola1 },
  { id: "dugtrio", pokemon: dugtrio },
  { id: "dugtrio1", pokemon: dugtrio1 },
  { id: "eevee", pokemon: eevee },
  { id: "eevee1", pokemon: eevee1 },
  { id: "ekans", pokemon: ekans },
  { id: "ekans1", pokemon: ekans1 },
  { id: "electabuzz", pokemon: electabuzz },
  { id: "electabuzz1", pokemon: electabuzz1 },
  { id: "electrode", pokemon: electrode },
  { id: "electrode1", pokemon: electrode1 },
  { id: "exeggcute", pokemon: exeggcute },
  { id: "exeggcute1", pokemon: exeggcute1 },
  { id: "exeggutorAlola", pokemon: exeggutorAlola },
  { id: "exeggutorAlola1", pokemon: exeggutorAlola1 },
  { id: "exeggutor", pokemon: exeggutor },
  { id: "exeggutor1", pokemon: exeggutor1 },
  { id: "farfetchd", pokemon: farfetchd },
  { id: "farfetchd1", pokemon: farfetchd1 },
  { id: "fearow", pokemon: fearow },
  { id: "fearow1", pokemon: fearow1 },
  { id: "flareon", pokemon: flareon },
  { id: "flareon1", pokemon: flareon1 },
  { id: "gastly", pokemon: gastly },
  { id: "gastly1", pokemon: gastly1 },
  { id: "gengarMega", pokemon: gengarMega },
  { id: "gengarMega1", pokemon: gengarMega1 },
  { id: "gengar", pokemon: gengar },
  { id: "gengar1", pokemon: gengar1 },
  { id: "geodudeAlola", pokemon: geodudeAlola },
  { id: "geodudeAlola1", pokemon: geodudeAlola1 },
  { id: "geodude", pokemon: geodude },
  { id: "geodude1", pokemon: geodude1 },
  { id: "gloomF", pokemon: gloomF },
  { id: "gloomF1", pokemon: gloomF1 },
  { id: "gloom", pokemon: gloom },
  { id: "gloom1", pokemon: gloom1 },
  { id: "golbatF", pokemon: golbatF },
  { id: "golbatF1", pokemon: golbatF1 },
  { id: "golbat", pokemon: golbat },
  { id: "golbat1", pokemon: golbat1 },
  { id: "goldeenF", pokemon: goldeenF },
  { id: "goldeenF1", pokemon: goldeenF1 },
  { id: "goldeen", pokemon: goldeen },
  { id: "goldeen1", pokemon: goldeen1 },
  { id: "golduck", pokemon: golduck },
  { id: "golduck1", pokemon: golduck1 },
  { id: "golemAlola", pokemon: golemAlola },
  { id: "golemAlola1", pokemon: golemAlola1 },
  { id: "golem", pokemon: golem },
  { id: "golem1", pokemon: golem1 },
  { id: "gravelerAlola", pokemon: gravelerAlola },
  { id: "gravelerAlola1", pokemon: gravelerAlola1 },
  { id: "graveler", pokemon: graveler },
  { id: "graveler1", pokemon: graveler1 },
  { id: "grimerAlola", pokemon: grimerAlola },
  { id: "grimerAlola1", pokemon: grimerAlola1 },
  { id: "grimer", pokemon: grimer },
  { id: "grimer1", pokemon: grimer1 },
  { id: "growlithe", pokemon: growlithe },
  { id: "growlithe1", pokemon: growlithe1 },
  { id: "gyaradosF", pokemon: gyaradosF },
  { id: "gyaradosF1", pokemon: gyaradosF1 },
  { id: "gyaradosMega", pokemon: gyaradosMega },
  { id: "gyaradosMega1", pokemon: gyaradosMega1 },
  { id: "gyarados", pokemon: gyarados },
  { id: "gyarados1", pokemon: gyarados1 },
  { id: "haunter", pokemon: haunter },
  { id: "haunter1", pokemon: haunter1 },
  { id: "hitmonchan", pokemon: hitmonchan },
  { id: "hitmonchan1", pokemon: hitmonchan1 },
  { id: "hitmonlee", pokemon: hitmonlee },
  { id: "hitmonlee1", pokemon: hitmonlee1 },
  { id: "horsea", pokemon: horsea },
  { id: "horsea1", pokemon: horsea1 },
  { id: "hypnoF", pokemon: hypnoF },
  { id: "hypnoF1", pokemon: hypnoF1 },
  { id: "hypno", pokemon: hypno },
  { id: "hypno1", pokemon: hypno1 },
  { id: "ivysaur", pokemon: ivysaur },
  { id: "ivysaur1", pokemon: ivysaur1 },

  { id: "jigglypuff", pokemon: jigglypuff },
  { id: "jigglypuff1", pokemon: jigglypuff1 },

  { id: "jigglypuF", pokemon: jigglypuF },
  { id: "jigglypuF1", pokemon: jigglypuF1 },
  { id: "jolteon", pokemon: jolteon },
  { id: "jolteon1", pokemon: jolteon1 },
  { id: "jynx", pokemon: jynx },
  { id: "jynx1", pokemon: jynx1 },
  { id: "kabuto", pokemon: kabuto },
  { id: "kabuto1", pokemon: kabuto1 },
  { id: "kabutops", pokemon: kabutops },
  { id: "kabutops1", pokemon: kabutops1 },
  { id: "kadabraF", pokemon: kadabraF },
  { id: "kadabraF1", pokemon: kadabraF1 },
  { id: "kadabra", pokemon: kadabra },
  { id: "kadabra1", pokemon: kadabra1 },
  { id: "kakuna", pokemon: kakuna },
  { id: "kakuna1", pokemon: kakuna1 },
  { id: "kangaskhanMega", pokemon: kangaskhanMega },
  { id: "kangaskhanMega1", pokemon: kangaskhanMega1 },
  { id: "kangaskhan", pokemon: kangaskhan },
  { id: "kangaskhan1", pokemon: kangaskhan1 },
  { id: "kingler", pokemon: kingler },
  { id: "kingler1", pokemon: kingler1 },
  { id: "koffing", pokemon: koffing },
  { id: "koffing1", pokemon: koffing1 },
  { id: "krabby", pokemon: krabby },
  { id: "krabby1", pokemon: krabby1 },
  { id: "lapras", pokemon: lapras },
  { id: "lapras1", pokemon: lapras1 },
  { id: "lickitung", pokemon: lickitung },
  { id: "lickitung1", pokemon: lickitung1 },
  { id: "machamp", pokemon: machamp },
  { id: "machamp1", pokemon: machamp1 },
  { id: "machoke", pokemon: machoke },
  { id: "machoke1", pokemon: machoke1 },
  { id: "machop", pokemon: machop },
  { id: "machop1", pokemon: machop1 },
  { id: "magikarpF", pokemon: magikarpF },
  { id: "magikarp", pokemon: magikarp },
  { id: "magikarp1", pokemon: magikarp1 },
  { id: "magmar", pokemon: magmar },
  { id: "magmar1", pokemon: magmar1 },
  { id: "magnemite", pokemon: magnemite },
  { id: "magnemite1", pokemon: magnemite1 },
  { id: "magneton", pokemon: magneton },
  { id: "magneton1", pokemon: magneton1 },
  { id: "mankey", pokemon: mankey },
  { id: "mankey1", pokemon: mankey1 },
  { id: "marowakAlola", pokemon: marowakAlola },
  { id: "marowakAlola1", pokemon: marowakAlola1 },
  { id: "marowakTotem", pokemon: marowakTotem },
  { id: "marowakTotem1", pokemon: marowakTotem1 },
  { id: "marowak", pokemon: marowak },
  { id: "marowak1", pokemon: marowak1 },
  { id: "meowthAlola", pokemon: meowthAlola },
  { id: "meowthAlola1", pokemon: meowthAlola1 },
  { id: "meowth", pokemon: meowth },
  { id: "meowth1", pokemon: meowth1 },
  { id: "metapod", pokemon: metapod },
  { id: "metapod1", pokemon: metapod1 },
  { id: "mew", pokemon: mew },
  { id: "mew1", pokemon: mew1 },
  { id: "mewtwoMegax", pokemon: mewtwoMegax },
  { id: "mewtwoMegax1", pokemon: mewtwoMegax1 },
  { id: "mewtwoMegay", pokemon: mewtwoMegay },
  { id: "mewtwoMegay1", pokemon: mewtwoMegay1 },
  { id: "mewtwo", pokemon: mewtwo },
  { id: "mewtwo1", pokemon: mewtwo1 },
  { id: "moltres", pokemon: moltres },
  { id: "moltres1", pokemon: moltres1 },
  { id: "mrMime", pokemon: mrMime },
  { id: "mr_Mime", pokemon: mr_Mime },
  { id: "mr0_Mime", pokemon: mr0_Mime },
  { id: "mr1_Mime", pokemon: mr1_Mime },
  { id: "mukAlola", pokemon: mukAlola },
  { id: "mukAlola1", pokemon: mukAlola1 },
  { id: "muk", pokemon: muk },
  { id: "muk1", pokemon: muk1 },
  { id: "nidoking", pokemon: nidoking },
  { id: "nidoking1", pokemon: nidoking1 },
  { id: "nidoqueen", pokemon: nidoqueen },
  { id: "nidoqueen1", pokemon: nidoqueen1 },
  { id: "nidoran_f", pokemon: nidoran_f },
  { id: "nidoran_f1", pokemon: nidoran_f1 },
  { id: "nidoran_m", pokemon: nidoran_m },
  { id: "nidoran_m1", pokemon: nidoran_m1 },
  { id: "nidorina", pokemon: nidorina },
  { id: "nidorina1", pokemon: nidorina1 },
  { id: "nidorino", pokemon: nidorino },
  { id: "nidorino1", pokemon: nidorino1 },
  { id: "ninetalesAlola", pokemon: ninetalesAlola },
  { id: "ninetalesAlola1", pokemon: ninetalesAlola1 },
  { id: "ninetales", pokemon: ninetales },
  { id: "ninetales1", pokemon: ninetales1 },
  { id: "oddish", pokemon: oddish },
  { id: "oddish1", pokemon: oddish1 },
  { id: "omanyte", pokemon: omanyte },
  { id: "omanyte1", pokemon: omanyte1 },
  { id: "omastar", pokemon: omastar },
  { id: "omastar1", pokemon: omastar1 },
  { id: "onix", pokemon: onix },
  { id: "onix1", pokemon: onix1 },
  { id: "paras", pokemon: paras },
  { id: "paras1", pokemon: paras1 },
  { id: "parasect", pokemon: parasect },
  { id: "parasect1", pokemon: parasect1 },
  { id: "persianAlola", pokemon: persianAlola },
  { id: "persianAlola1", pokemon: persianAlola1 },
  { id: "persian", pokemon: persian },
  { id: "persian1", pokemon: persian1 },
  { id: "pidgeot", pokemon: pidgeot },
  { id: "pidgeot1", pokemon: pidgeot1 },
  { id: "pidgeotto", pokemon: pidgeotto },
  { id: "pidgeotto1", pokemon: pidgeotto1 },
  { id: "pidgey", pokemon: pidgey },
  { id: "pidgey1", pokemon: pidgey1 },
  { id: "pikachu_alolacap", pokemon: pikachu_alolacap },
  { id: "pikachu_belle", pokemon: pikachu_belle },
  { id: "pikachu_belle1", pokemon: pikachu_belle1 },
  { id: "pikachu_cosplay", pokemon: pikachu_cosplay },
  { id: "pikachu_cosplay1", pokemon: pikachu_cosplay1 },
  { id: "pikachuF", pokemon: pikachuF },
  { id: "pikachuF1", pokemon: pikachuF1 },
  { id: "pikachu_hoenncap", pokemon: pikachu_hoenncap },
  { id: "pikachu_kaloscap", pokemon: pikachu_kaloscap },
  { id: "pikachu_kantocap", pokemon: pikachu_kantocap },
  { id: "pikachu_libre", pokemon: pikachu_libre },
  { id: "pikachu_partnercap", pokemon: pikachu_partnercap },
  { id: "pikachu_phd", pokemon: pikachu_phd },
  { id: "pikachu_phd1", pokemon: pikachu_phd1 },
  { id: "pikachu_popstar", pokemon: pikachu_popstar },
  { id: "pikachu_popstar1", pokemon: pikachu_popstar1 },
  { id: "pikachu_rockstar", pokemon: pikachu_rockstar },
  { id: "pikachu_rockstar1", pokemon: pikachu_rockstar1 },
  { id: "pikachu_sinnohcap", pokemon: pikachu_sinnohcap },
  { id: "pikachu_unovacap", pokemon: pikachu_unovacap },
  { id: "pikachu", pokemon: pikachu },
  { id: "pikachu1", pokemon: pikachu1 },
  { id: "pinsirMega", pokemon: pinsirMega },
  { id: "pinsirMega1", pokemon: pinsirMega1 },
  { id: "pinsir", pokemon: pinsir },
  { id: "pinsir1", pokemon: pinsir1 },
  { id: "poliwag", pokemon: poliwag },
  { id: "poliwag1", pokemon: poliwag1 },
  { id: "poliwhirl", pokemon: poliwhirl },
  { id: "poliwhirl1", pokemon: poliwhirl1 },
  { id: "poliwrath", pokemon: poliwrath },
  { id: "poliwrath1", pokemon: poliwrath1 },
  { id: "ponyta", pokemon: ponyta },
  { id: "ponyta1", pokemon: ponyta1 },
  { id: "porygon", pokemon: porygon },
  { id: "porygon1", pokemon: porygon1 },
  { id: "primeape", pokemon: primeape },
  { id: "primeape1", pokemon: primeape1 },
  { id: "psyduck", pokemon: psyduck },
  { id: "psyduck1", pokemon: psyduck1 },
  { id: "raichuAlola", pokemon: raichuAlola },
  { id: "raichuAlola1", pokemon: raichuAlola1 },
  { id: "raichuF", pokemon: raichuF },
  { id: "raichuF1", pokemon: raichuF1 },
  { id: "raichu", pokemon: raichu },
  { id: "raichu1", pokemon: raichu1 },
  { id: "rapidash", pokemon: rapidash },
  { id: "rapidash1", pokemon: rapidash1 },
  { id: "raticateAlola", pokemon: raticateAlola },
  { id: "raticateAlola1", pokemon: raticateAlola1 },
  { id: "raticateF", pokemon: raticateF },
  { id: "raticateF1", pokemon: raticateF1 },
  { id: "raticateTotem", pokemon: raticateTotem },
  { id: "raticateTotem1", pokemon: raticateTotem1 },
  { id: "raticate", pokemon: raticate },
  { id: "raticate1", pokemon: raticate1 },
  { id: "rattataAlola", pokemon: rattataAlola },
  { id: "rattataAlola1", pokemon: rattataAlola1 },
  { id: "rattataF", pokemon: rattataF },
  { id: "rattataF1", pokemon: rattataF1 },
  { id: "rattata", pokemon: rattata },
  { id: "rattata1", pokemon: rattata1 },
  { id: "rhydonF", pokemon: rhydonF },
  { id: "rhydon", pokemon: rhydon },
  { id: "rhydon1", pokemon: rhydon1 },
  { id: "rhyhornF", pokemon: rhyhornF },
  { id: "rhyhornF1", pokemon: rhyhornF1 },
  { id: "rhyhorn", pokemon: rhyhorn },
  { id: "rhyhorn1", pokemon: rhyhorn1 },
  { id: "sandshrewAlola", pokemon: sandshrewAlola },
  { id: "sandshrewAlola1", pokemon: sandshrewAlola1 },
  { id: "sandshrew", pokemon: sandshrew },
  { id: "sandshrew1", pokemon: sandshrew1 },
  { id: "sandslashAlola", pokemon: sandslashAlola },
  { id: "sandslashAlola1", pokemon: sandslashAlola1 },
  { id: "sandslash", pokemon: sandslash },
  { id: "sandslash1", pokemon: sandslash1 },
  { id: "scytherF", pokemon: scytherF },
  { id: "scyther", pokemon: scyther },
  { id: "scyther1", pokemon: scyther1 },
  { id: "seadra", pokemon: seadra },
  { id: "seadra1", pokemon: seadra1 },
  { id: "seakingF", pokemon: seakingF },
  { id: "seakingF1", pokemon: seakingF1 },
  { id: "seaking", pokemon: seaking },
  { id: "seaking1", pokemon: seaking1 },
  { id: "seel", pokemon: seel },
  { id: "seel1", pokemon: seel1 },
  { id: "shellder", pokemon: shellder },
  { id: "shellder1", pokemon: shellder1 },
  { id: "slowbroMega", pokemon: slowbroMega },
  { id: "slowbroMega1", pokemon: slowbroMega1 },
  { id: "slowbro", pokemon: slowbro },
  { id: "slowbro1", pokemon: slowbro1 },
  { id: "slowpoke", pokemon: slowpoke },
  { id: "slowpoke1", pokemon: slowpoke1 },
  { id: "snorlax", pokemon: snorlax },
  { id: "snorlax1", pokemon: snorlax1 },
  { id: "spearow", pokemon: spearow },
  { id: "spearow1", pokemon: spearow1 },
  { id: "squirtle", pokemon: squirtle },
  { id: "squirtle1", pokemon: squirtle1 },
  { id: "starmie", pokemon: starmie },
  { id: "starmie1", pokemon: starmie1 },
  { id: "staryu", pokemon: staryu },
  { id: "staryu1", pokemon: staryu1 },
  { id: "tangela", pokemon: tangela },
  { id: "tangela1", pokemon: tangela1 },
  { id: "tauros", pokemon: tauros },
  { id: "tauros1", pokemon: tauros1 },
  { id: "tentacool", pokemon: tentacool },
  { id: "tentacool1", pokemon: tentacool1 },
  { id: "tentacruel", pokemon: tentacruel },
  { id: "tentacruel1", pokemon: tentacruel1 },
  { id: "vaporeon", pokemon: vaporeon },
  { id: "vaporeon1", pokemon: vaporeon1 },
  { id: "venomoth", pokemon: venomoth },
  { id: "venomoth1", pokemon: venomoth1 },
  { id: "venonat", pokemon: venonat },
  { id: "venonat1", pokemon: venonat1 },
  { id: "venusaurF", pokemon: venusaurF },
  { id: "venusaurF1", pokemon: venusaurF1 },
  { id: "venusaurMega", pokemon: venusaurMega },
  { id: "venusaurMega1", pokemon: venusaurMega1 },
  { id: "venusaur", pokemon: venusaur },
  { id: "venusaur1", pokemon: venusaur1 },
  { id: "victreebel", pokemon: victreebel },
  { id: "victreebel1", pokemon: victreebel1 },
  { id: "vileplumeF", pokemon: vileplumeF },
  { id: "vileplumeF1", pokemon: vileplumeF1 },
  { id: "vileplume", pokemon: vileplume },
  { id: "vileplume1", pokemon: vileplume1 },
  { id: "voltorb", pokemon: voltorb },
  { id: "voltorb1", pokemon: voltorb1 },
  { id: "vulpixAlola", pokemon: vulpixAlola },
  { id: "vulpixAlola1", pokemon: vulpixAlola1 },
  { id: "vulpix", pokemon: vulpix },
  { id: "vulpix1", pokemon: vulpix1 },
  { id: "wartortle", pokemon: wartortle },
  { id: "wartortle1", pokemon: wartortle1 },
  { id: "weedle", pokemon: weedle },
  { id: "weedle1", pokemon: weedle1 },
  { id: "weepinbell", pokemon: weepinbell },
  { id: "weepinbell1", pokemon: weepinbell1 },
  { id: "weezing", pokemon: weezing },
  { id: "weezing1", pokemon: weezing1 },
  { id: "wigglytuff", pokemon: wigglytuff },
  { id: "wigglytuff1", pokemon: wigglytuff1 },
  { id: "wigglytuF", pokemon: wigglytuF },
  { id: "wigglytuF1", pokemon: wigglytuF1 },
  { id: "zapdos", pokemon: zapdos },
  { id: "zapdos1", pokemon: zapdos1 },
  { id: "zubatF", pokemon: zubatF },
  { id: "zubatF1", pokemon: zubatF1 },
  { id: "zubat", pokemon: zubat },
  { id: "zubat1", pokemon: zubat1 },
];
let randomize = Math.floor(Math.random() * pokemonAssetArr.length);

const PokemonAsset = ({ pokemonLoaded }) => {
  const { state } = useContext(AppContext);

  console.log("pokemonLoaded val", pokemonLoaded);
  let foundObj = pokemonAssetArr.find((i) => {
    return pokemonLoaded === "nidoran-f"
      ? i.id === "nidoran_f"
      : pokemonLoaded === "nidoran-m"
      ? i.id === "nidoran_m"
      : pokemonLoaded === "mr-mime"
      ? i.id === "mrMime"
      : i.id === pokemonLoaded;
  });

  return (
    <img
      alt="pokemon"
      src={foundObj.pokemon}
      style={{ maxHeight: 150, height: 100 }}
    />
  );
};
//

export default PokemonAsset;
