import React from "react";
import {
  abra,
  abra1,
  aerodactylMega,
  aerodactylMega1,
  aerodactyl,
  aerodactyl1,
  alakazamF,
  alakazamMega,
  alakazamMega1,
  alakazam,
  alakazam1,
  arbok,
  arbok1,
  arcanine,
  arcanine1,
  articuno,
  articuno1,
  beedrillMega,
  beedrillMega1,
  beedrill,
  beedrill1,
  bellsprout,
  bellsprout1,
  blastoiseMega,
  blastoiseMega1,
  blastoise,
  blastoise1,
  bulbasaur,
  bulbasaur1,
  butterfreeF,
  butterfreeF1,
  butterfree,
  butterfree1,
  caterpie,
  caterpie1,
  chansey,
  chansey1,
  charizardMegax,
  charizardMegax1,
  charizardMegay,
  charizardMegay1,
  charizard,
  charizard1,
  charmander,
  charmander1,
  charmeleon,
  charmeleon1,
  clefable,
  clefable1,
  clefairy,
  clefairy1,
  cloyster,
  cloyster1,
  cubone,
  cubone1,
  dewgong,
  dewgong1,
  diglettAlola,
  diglettAlola1,
  diglett,
  diglett1,
  ditto,
  ditto1,
  dodrioF,
  dodrioF1,
  dodrio,
  dodrio1,
  doduoF,
  doduoF1,
  doduo,
  doduo1,
  dragonair,
  dragonair1,
  dragonite,
  dragonite1,
  dratini,
  dratini1,
  drowzee,
  drowzee1,
  dugtrioAlola,
  dugtrioAlola1,
  dugtrio,
  dugtrio1,
  eevee,
  eevee1,
  ekans,
  ekans1,
  electabuzz,
  electabuzz1,
  electrode,
  electrode1,
  exeggcute,
  exeggcute1,
  exeggutorAlola,
  exeggutorAlola1,
  exeggutor,
  exeggutor1,
  farfetchd,
  farfetchd1,
  fearow,
  fearow1,
  flareon,
  flareon1,
  gastly,
  gastly1,
  gengarMega,
  gengarMega1,
  gengar,
  gengar1,
  geodudeAlola,
  geodudeAlola1,
  geodude,
  geodude1,
  gloomF,
  gloomF1,
  gloom,
  gloom1,
  golbatF,
  golbatF1,
  golbat,
  golbat1,
  goldeenF,
  goldeenF1,
  goldeen,
  goldeen1,
  golduck,
  golduck1,
  golemAlola,
  golemAlola1,
  golem,
  golem1,
  gravelerAlola,
  gravelerAlola1,
  graveler,
  graveler1,
  grimerAlola,
  grimerAlola1,
  grimer,
  grimer1,
  growlithe,
  growlithe1,
  gyaradosF,
  gyaradosF1,
  gyaradosMega,
  gyaradosMega1,
  gyarados,
  gyarados1,
  haunter,
  haunter1,
  hitmonchan,
  hitmonchan1,
  hitmonlee,
  hitmonlee1,
  horsea,
  horsea1,
  hypnoF,
  hypnoF1,
  hypno,
  hypno1,
  ivysaur,
  ivysaur1,
  jigglypuff,
  jigglypuff1,
  jigglypuF,
  jigglypuF1,
  jolteon,
  jolteon1,
  jynx,
  jynx1,
  kabuto,
  kabuto1,
  kabutops,
  kabutops1,
  kadabraF,
  kadabraF1,
  kadabra,
  kadabra1,
  kakuna,
  kakuna1,
  kangaskhanMega,
  kangaskhanMega1,
  kangaskhan,
  kangaskhan1,
  kingler,
  kingler1,
  koffing,
  koffing1,
  krabby,
  krabby1,
  lapras,
  lapras1,
  lickitung,
  lickitung1,
  machamp,
  machamp1,
  machoke,
  machoke1,
  machop,
  machop1,
  magikarpF,
  magikarp,
  magikarp1,
  magmar,
  magmar1,
  magnemite,
  magnemite1,
  magneton,
  magneton1,
  mankey,
  mankey1,
  marowakAlola,
  marowakAlola1,
  marowakTotem,
  marowakTotem1,
  marowak,
  marowak1,
  meowthAlola,
  meowthAlola1,
  meowth,
  meowth1,
  metapod,
  metapod1,
  mew,
  mew1,
  mewtwoMegax,
  mewtwoMegax1,
  mewtwoMegay,
  mewtwoMegay1,
  mewtwo,
  mewtwo1,
  moltres,
  moltres1,
  mrMime,
  mr_Mime,
  mr0_Mime,
  mr1_Mime,
  mukAlola,
  mukAlola1,
  muk,
  muk1,
  nidoking,
  nidoking1,
  nidoqueen,
  nidoqueen1,
  nidoran_f,
  nidoran_f1,
  nidoran_m,
  nidoran_m1,
  nidorina,
  nidorina1,
  nidorino,
  nidorino1,
  ninetalesAlola,
  ninetalesAlola1,
  ninetales,
  ninetales1,
  oddish,
  oddish1,
  omanyte,
  omanyte1,
  omastar,
  omastar1,
  onix,
  onix1,
  paras,
  paras1,
  parasect,
  parasect1,
  persianAlola,
  persianAlola1,
  persian,
  persian1,
  pidgeot,
  pidgeot1,
  pidgeotto,
  pidgeotto1,
  pidgey,
  pidgey1,
  pikachu_alolacap,
  pikachu_belle,
  pikachu_belle1,
  pikachu_cosplay,
  pikachu_cosplay1,
  pikachuF,
  pikachuF1,
  pikachu_hoenncap,
  pikachu_kaloscap,
  pikachu_kantocap,
  pikachu_libre,
  pikachu_partnercap,
  pikachu_phd,
  pikachu_phd1,
  pikachu_popstar,
  pikachu_popstar1,
  pikachu_rockstar,
  pikachu_rockstar1,
  pikachu_sinnohcap,
  pikachu_unovacap,
  pikachu,
  pikachu1,
  pinsirMega,
  pinsirMega1,
  pinsir,
  pinsir1,
  poliwag,
  poliwag1,
  poliwhirl,
  poliwhirl1,
  poliwrath,
  poliwrath1,
  ponyta,
  ponyta1,
  porygon,
  porygon1,
  primeape,
  primeape1,
  psyduck,
  psyduck1,
  raichuAlola,
  raichuAlola1,
  raichuF,
  raichuF1,
  raichu,
  raichu1,
  rapidash,
  rapidash1,
  raticateAlola,
  raticateAlola1,
  raticateF,
  raticateF1,
  raticateTotem,
  raticateTotem1,
  raticate,
  raticate1,
  rattataAlola,
  rattataAlola1,
  rattataF,
  rattataF1,
  rattata,
  rattata1,
  rhydonF,
  rhydon,
  rhydon1,
  rhyhornF,
  rhyhornF1,
  rhyhorn,
  rhyhorn1,
  sandshrewAlola,
  sandshrewAlola1,
  sandshrew,
  sandshrew1,
  sandslashAlola,
  sandslashAlola1,
  sandslash,
  sandslash1,
  scytherF,
  scyther,
  scyther1,
  seadra,
  seadra1,
  seakingF,
  seakingF1,
  seaking,
  seaking1,
  seel,
  seel1,
  shellder,
  shellder1,
  slowbroMega,
  slowbroMega1,
  slowbro,
  slowbro1,
  slowpoke,
  slowpoke1,
  snorlax,
  snorlax1,
  spearow,
  spearow1,
  squirtle,
  squirtle1,
  starmie,
  starmie1,
  staryu,
  staryu1,
  tangela,
  tangela1,
  tauros,
  tauros1,
  tentacool,
  tentacool1,
  tentacruel,
  tentacruel1,
  vaporeon,
  vaporeon1,
  venomoth,
  venomoth1,
  venonat,
  venonat1,
  venusaurF,
  venusaurF1,
  venusaurMega,
  venusaurMega1,
  venusaur,
  venusaur1,
  victreebel,
  victreebel1,
  vileplumeF,
  vileplumeF1,
  vileplume,
  vileplume1,
  voltorb,
  voltorb1,
  vulpixAlola,
  vulpixAlola1,
  vulpix,
  vulpix1,
  wartortle,
  wartortle1,
  weedle,
  weedle1,
  weepinbell,
  weepinbell1,
  weezing,
  weezing1,
  wigglytuff,
  wigglytuff1,
  wigglytuF,
  wigglytuF1,
  zapdos,
  zapdos1,
  zubatF,
  zubatF1,
  zubat,
  zubat1,

  //gen2
  aipom_f,
  aipom_f1,
  aipom,
  aipom1,
  ampharos_mega,
  ampharos_mega1,
  ampharos,
  ampharos1,
  ariados,
  ariados1,
  azumarill,
  azumarill1,
  bayleef,
  bayleef1,
  bellossom,
  bellossom1,
  blissey,
  blissey1,
  celebi,
  celebi1,
  chikorita,
  chikorita1,
  chinchou,
  chinchou1,
  cleffa,
  cleffa1,
  corsola,
  corsola1,
  crobat,
  crobat1,
  croconaw,
  croconaw1,
  cyndaquil,
  cyndaquil1,
  delibird,
  delibird1,
  donphan_f,
  donphan_f1,
  donphan,
  donphan1,
  dunsparce,
  dunsparce1,
  elekid,
  elekid1,
  entei,
  entei1,
  espeon,
  espeon1,
  feraligatr,
  feraligatr1,
  flaaffy,
  flaaffy1,
  forretress,
  forretress1,
  furret,
  furret1,
  girafarig_f,
  girafarig_f1,
  girafarig,
  girafarig1,
  gligar_f,
  gligar_f1,
  gligar,
  gligar1,
  granbull,
  granbull1,
  heracross_f,
  heracross_f1,
  heracross_mega,
  heracross_mega1,
  heracross,
  heracross1,
  hitmontop,
  hitmontop1,
  ho_oh,
  ho_oh1,
  hoothoot,
  hoothoot1,
  hoppip,
  hoppip1,
  houndoom_f,
  houndoom_f1,
  houndoom_mega,
  houndoom_mega1,
  houndoom,
  houndoom1,
  houndour,
  houndour1,
  igglybuff,
  igglybuff1,
  jumpluff,
  jumpluff1,
  kingdra,
  kingdra1,
  lanturn,
  lanturn1,
  larvitar,
  larvitar1,
  ledian_f,
  ledian_f1,
  ledian,
  ledian1,
  ledyba_f,
  ledyba_f1,
  ledyba,
  ledyba1,
  lugia,
  lugia1,
  magby,
  magby1,
  magcargo,
  magcargo1,
  mantine,
  mantine1,
  mareep,
  mareep1,
  marill,
  marill1,
  meganium_f,
  meganium_f1,
  meganium,
  meganium1,
  miltank,
  miltank1,
  misdreavus,
  misdreavus1,
  murkrow_f,
  murkrow_f1,
  murkrow,
  murkrow1,
  natu,
  natu1,
  noctowl,
  noctowl1,
  octillery_f,
  octillery_f1,
  octillery,
  octillery1,
  phanpy,
  phanpy1,
  pichu,
  pichu1,
  piloswine_f,
  piloswine_f1,
  piloswine,
  piloswine1,
  pineco,
  pineco1,
  politoed_f,
  politoed_f1,
  politoed,
  porygon2,
  porygon21,
  pupitar,
  pupitar1,
  quagsire_f,
  quagsire_f1,
  quagsire,
  quagsire1,
  quilava,
  quilava1,
  qwilfish,
  qwilfish1,
  raikou,
  raikou1,
  remoraid,
  remoraid1,
  scizor_f,
  scizor_f1,
  scizor_mega,
  scizor_mega1,
  scizor,
  scizor1,
  sentret,
  sentret1,
  shuckle,
  shuckle1,
  skarmory,
  skarmory1,
  skiploom,
  skiploom1,
  slowking,
  slowking1,
  slugma,
  slugma1,
  smeargle,
  smeargle1,
  smoochum,
  smoochum1,
  sneasel_f,
  sneasel_f1,
  sneasel,
  sneasel1,
  snubbull,
  snubbull1,
  spinarak,
  spinarak1,
  stantler,
  stantler1,
  steelix_f,
  steelix_f1,
  steelix_mega,
  steelix_mega1,
  steelix,
  steelix1,
  sudowoodo_f,
  sudowoodo_f1,
  sudowoodo,
  sudowoodo1,
  suicune,
  suicune1,
  sunflora,
  sunflora1,
  sunkern,
  sunkern1,
  swinub,
  swinub1,
  teddiursa,
  teddiursa1,
  togepi,
  togepi1,
  togetic,
  togetic1,
  totodile,
  totodile1,
  typhlosion,
  typhlosion1,
  tyranitar_mega,
  tyranitar_mega1,
  tyranitar,
  tyranitar1,
  tyrogue,
  tyrogue1,
  umbreon,
  umbreon1,
  unown_bravo,
  unown_bravo1,
  unown_charlie,
  unown_charlie1,
  unown_delta,
  unown_delta1,
  unown_echo,
  unown_echo1,
  unown_exclamation,
  unown_exclamation1,
  unown_foxtrot,
  unown_foxtrot1,
  unown_golf,
  unown_golf1,
  unown_hotel,
  unown_hotel1,
  unown_india,
  unown_india1,
  unown_interrogation,
  unown_interrogation1,
  unown_juliet,
  unown_juliet1,
  unown_kilo,
  unown_kilo1,
  unown_lima,
  unown_lima1,
  unown_mike,
  unown_mike1,
  unown_november,
  unown_november1,
  unown_oscar,
  unown_oscar1,
  unown_papa,
  unown_papa1,
  unown_quebec,
  unown_quebec1,
  unown_romeo,
  unown_romeo1,
  unown_sierra,
  unown_sierra1,
  unown_tango,
  unown_tango1,
  unown_uniform,
  unown_uniform1,
  unown_victor,
  unown_victor1,
  unown_whiskey,
  unown_whiskey1,
  unown_xray,
  unown_xray1,
  unown_yankee,
  unown_yankee1,
  unown_zulu,
  unown_zulu1,
  unown,
  unown1,
  ursaring_f,
  ursaring_f1,
  ursaring,
  ursaring1,
  wobbuffet_f,
  wobbuffet_f1,
  wobbuffet,
  wobbuffet1,
  wooper_f,
  wooper_f1,
  wooper,
  wooper1,
  xatu_f,
  xatu_f1,
  xatu,
  xatu1,
  yanma,
  yanma1,
} from "../assets/pokedex";

const pokemonAssetArr = [
  //gen1
  { id: "abra", pokemon: abra },
  { id: "abra1", pokemon: abra1 },
  { id: "aerodactylMega", pokemon: aerodactylMega },
  { id: "aerodactylMega1", pokemon: aerodactylMega1 },
  { id: "aerodactyl", pokemon: aerodactyl },
  { id: "aerodactyl1", pokemon: aerodactyl1 },
  { id: "alakazamF", pokemon: alakazamF },
  { id: "alakazamMega", pokemon: alakazamMega },
  { id: "alakazamMega1", pokemon: alakazamMega1 },
  { id: "alakazam", pokemon: alakazam },
  { id: "alakazam1", pokemon: alakazam1 },
  { id: "arbok", pokemon: arbok },
  { id: "arbok1", pokemon: arbok1 },
  { id: "arcanine", pokemon: arcanine },
  { id: "arcanine1", pokemon: arcanine1 },
  { id: "articuno", pokemon: articuno },
  { id: "articuno1", pokemon: articuno1 },
  { id: "beedrillMega", pokemon: beedrillMega },
  { id: "beedrillMega1", pokemon: beedrillMega1 },
  { id: "beedrill", pokemon: beedrill },
  { id: "beedrill1", pokemon: beedrill1 },
  { id: "bellsprout", pokemon: bellsprout },
  { id: "bellsprout1", pokemon: bellsprout1 },
  { id: "blastoiseMega", pokemon: blastoiseMega },
  { id: "blastoiseMega1", pokemon: blastoiseMega1 },
  { id: "blastoise", pokemon: blastoise },
  { id: "blastoise1", pokemon: blastoise1 },
  { id: "bulbasaur", pokemon: bulbasaur },
  { id: "bulbasaur1", pokemon: bulbasaur1 },
  { id: "butterfreeF", pokemon: butterfreeF },
  { id: "butterfreeF1", pokemon: butterfreeF1 },
  { id: "butterfree", pokemon: butterfree },
  { id: "butterfree1", pokemon: butterfree1 },
  { id: "caterpie", pokemon: caterpie },
  { id: "caterpie1", pokemon: caterpie1 },
  { id: "chansey", pokemon: chansey },
  { id: "chansey1", pokemon: chansey1 },
  { id: "charizardMegax", pokemon: charizardMegax },
  { id: "charizardMegax1", pokemon: charizardMegax1 },
  { id: "charizardMegay", pokemon: charizardMegay },
  { id: "charizardMegay1", pokemon: charizardMegay1 },
  { id: "charizard", pokemon: charizard },
  { id: "charizard1", pokemon: charizard1 },
  { id: "charmander", pokemon: charmander },
  { id: "charmander1", pokemon: charmander1 },
  { id: "charmeleon", pokemon: charmeleon },
  { id: "charmeleon1", pokemon: charmeleon1 },
  { id: "clefable", pokemon: clefable },
  { id: "clefable1", pokemon: clefable1 },
  { id: "clefairy", pokemon: clefairy },
  { id: "clefairy1", pokemon: clefairy1 },
  { id: "cloyster", pokemon: cloyster },
  { id: "cloyster1", pokemon: cloyster1 },
  { id: "cubone", pokemon: cubone },
  { id: "cubone1", pokemon: cubone1 },
  { id: "dewgong", pokemon: dewgong },
  { id: "dewgong1", pokemon: dewgong1 },
  { id: "diglettAlola", pokemon: diglettAlola },
  { id: "diglettAlola1", pokemon: diglettAlola1 },
  { id: "diglett", pokemon: diglett },
  { id: "diglett1", pokemon: diglett1 },
  { id: "ditto", pokemon: ditto },
  { id: "ditto1", pokemon: ditto1 },
  { id: "dodrioF", pokemon: dodrioF },
  { id: "dodrioF1", pokemon: dodrioF1 },
  { id: "dodrio", pokemon: dodrio },
  { id: "dodrio1", pokemon: dodrio1 },
  { id: "doduoF", pokemon: doduoF },
  { id: "doduoF1", pokemon: doduoF1 },
  { id: "doduo", pokemon: doduo },
  { id: "doduo1", pokemon: doduo1 },
  { id: "dragonair", pokemon: dragonair },
  { id: "dragonair1", pokemon: dragonair1 },
  { id: "dragonite", pokemon: dragonite },
  { id: "dragonite1", pokemon: dragonite1 },
  { id: "dratini", pokemon: dratini },
  { id: "dratini1", pokemon: dratini1 },
  { id: "drowzee", pokemon: drowzee },
  { id: "drowzee1", pokemon: drowzee1 },
  { id: "dugtrioAlola", pokemon: dugtrioAlola },
  { id: "dugtrioAlola1", pokemon: dugtrioAlola1 },
  { id: "dugtrio", pokemon: dugtrio },
  { id: "dugtrio1", pokemon: dugtrio1 },
  { id: "eevee", pokemon: eevee },
  { id: "eevee1", pokemon: eevee1 },
  { id: "ekans", pokemon: ekans },
  { id: "ekans1", pokemon: ekans1 },
  { id: "electabuzz", pokemon: electabuzz },
  { id: "electabuzz1", pokemon: electabuzz1 },
  { id: "electrode", pokemon: electrode },
  { id: "electrode1", pokemon: electrode1 },
  { id: "exeggcute", pokemon: exeggcute },
  { id: "exeggcute1", pokemon: exeggcute1 },
  { id: "exeggutorAlola", pokemon: exeggutorAlola },
  { id: "exeggutorAlola1", pokemon: exeggutorAlola1 },
  { id: "exeggutor", pokemon: exeggutor },
  { id: "exeggutor1", pokemon: exeggutor1 },
  { id: "farfetchd", pokemon: farfetchd },
  { id: "farfetchd1", pokemon: farfetchd1 },
  { id: "fearow", pokemon: fearow },
  { id: "fearow1", pokemon: fearow1 },
  { id: "flareon", pokemon: flareon },
  { id: "flareon1", pokemon: flareon1 },
  { id: "gastly", pokemon: gastly },
  { id: "gastly1", pokemon: gastly1 },
  { id: "gengarMega", pokemon: gengarMega },
  { id: "gengarMega1", pokemon: gengarMega1 },
  { id: "gengar", pokemon: gengar },
  { id: "gengar1", pokemon: gengar1 },
  { id: "geodudeAlola", pokemon: geodudeAlola },
  { id: "geodudeAlola1", pokemon: geodudeAlola1 },
  { id: "geodude", pokemon: geodude },
  { id: "geodude1", pokemon: geodude1 },
  { id: "gloomF", pokemon: gloomF },
  { id: "gloomF1", pokemon: gloomF1 },
  { id: "gloom", pokemon: gloom },
  { id: "gloom1", pokemon: gloom1 },
  { id: "golbatF", pokemon: golbatF },
  { id: "golbatF1", pokemon: golbatF1 },
  { id: "golbat", pokemon: golbat },
  { id: "golbat1", pokemon: golbat1 },
  { id: "goldeenF", pokemon: goldeenF },
  { id: "goldeenF1", pokemon: goldeenF1 },
  { id: "goldeen", pokemon: goldeen },
  { id: "goldeen1", pokemon: goldeen1 },
  { id: "golduck", pokemon: golduck },
  { id: "golduck1", pokemon: golduck1 },
  { id: "golemAlola", pokemon: golemAlola },
  { id: "golemAlola1", pokemon: golemAlola1 },
  { id: "golem", pokemon: golem },
  { id: "golem1", pokemon: golem1 },
  { id: "gravelerAlola", pokemon: gravelerAlola },
  { id: "gravelerAlola1", pokemon: gravelerAlola1 },
  { id: "graveler", pokemon: graveler },
  { id: "graveler1", pokemon: graveler1 },
  { id: "grimerAlola", pokemon: grimerAlola },
  { id: "grimerAlola1", pokemon: grimerAlola1 },
  { id: "grimer", pokemon: grimer },
  { id: "grimer1", pokemon: grimer1 },
  { id: "growlithe", pokemon: growlithe },
  { id: "growlithe1", pokemon: growlithe1 },
  { id: "gyaradosF", pokemon: gyaradosF },
  { id: "gyaradosF1", pokemon: gyaradosF1 },
  { id: "gyaradosMega", pokemon: gyaradosMega },
  { id: "gyaradosMega1", pokemon: gyaradosMega1 },
  { id: "gyarados", pokemon: gyarados },
  { id: "gyarados1", pokemon: gyarados1 },
  { id: "haunter", pokemon: haunter },
  { id: "haunter1", pokemon: haunter1 },
  { id: "hitmonchan", pokemon: hitmonchan },
  { id: "hitmonchan1", pokemon: hitmonchan1 },
  { id: "hitmonlee", pokemon: hitmonlee },
  { id: "hitmonlee1", pokemon: hitmonlee1 },
  { id: "horsea", pokemon: horsea },
  { id: "horsea1", pokemon: horsea1 },
  { id: "hypnoF", pokemon: hypnoF },
  { id: "hypnoF1", pokemon: hypnoF1 },
  { id: "hypno", pokemon: hypno },
  { id: "hypno1", pokemon: hypno1 },
  { id: "ivysaur", pokemon: ivysaur },
  { id: "ivysaur1", pokemon: ivysaur1 },
  { id: "jigglypuff", pokemon: jigglypuff },
  { id: "jigglypuff1", pokemon: jigglypuff1 },
  { id: "jigglypuF", pokemon: jigglypuF },
  { id: "jigglypuF1", pokemon: jigglypuF1 },
  { id: "jolteon", pokemon: jolteon },
  { id: "jolteon1", pokemon: jolteon1 },
  { id: "jynx", pokemon: jynx },
  { id: "jynx1", pokemon: jynx1 },
  { id: "kabuto", pokemon: kabuto },
  { id: "kabuto1", pokemon: kabuto1 },
  { id: "kabutops", pokemon: kabutops },
  { id: "kabutops1", pokemon: kabutops1 },
  { id: "kadabraF", pokemon: kadabraF },
  { id: "kadabraF1", pokemon: kadabraF1 },
  { id: "kadabra", pokemon: kadabra },
  { id: "kadabra1", pokemon: kadabra1 },
  { id: "kakuna", pokemon: kakuna },
  { id: "kakuna1", pokemon: kakuna1 },
  { id: "kangaskhanMega", pokemon: kangaskhanMega },
  { id: "kangaskhanMega1", pokemon: kangaskhanMega1 },
  { id: "kangaskhan", pokemon: kangaskhan },
  { id: "kangaskhan1", pokemon: kangaskhan1 },
  { id: "kingler", pokemon: kingler },
  { id: "kingler1", pokemon: kingler1 },
  { id: "koffing", pokemon: koffing },
  { id: "koffing1", pokemon: koffing1 },
  { id: "krabby", pokemon: krabby },
  { id: "krabby1", pokemon: krabby1 },
  { id: "lapras", pokemon: lapras },
  { id: "lapras1", pokemon: lapras1 },
  { id: "lickitung", pokemon: lickitung },
  { id: "lickitung1", pokemon: lickitung1 },
  { id: "machamp", pokemon: machamp },
  { id: "machamp1", pokemon: machamp1 },
  { id: "machoke", pokemon: machoke },
  { id: "machoke1", pokemon: machoke1 },
  { id: "machop", pokemon: machop },
  { id: "machop1", pokemon: machop1 },
  { id: "magikarpF", pokemon: magikarpF },
  { id: "magikarp", pokemon: magikarp },
  { id: "magikarp1", pokemon: magikarp1 },
  { id: "magmar", pokemon: magmar },
  { id: "magmar1", pokemon: magmar1 },
  { id: "magnemite", pokemon: magnemite },
  { id: "magnemite1", pokemon: magnemite1 },
  { id: "magneton", pokemon: magneton },
  { id: "magneton1", pokemon: magneton1 },
  { id: "mankey", pokemon: mankey },
  { id: "mankey1", pokemon: mankey1 },
  { id: "marowakAlola", pokemon: marowakAlola },
  { id: "marowakAlola1", pokemon: marowakAlola1 },
  { id: "marowakTotem", pokemon: marowakTotem },
  { id: "marowakTotem1", pokemon: marowakTotem1 },
  { id: "marowak", pokemon: marowak },
  { id: "marowak1", pokemon: marowak1 },
  { id: "meowthAlola", pokemon: meowthAlola },
  { id: "meowthAlola1", pokemon: meowthAlola1 },
  { id: "meowth", pokemon: meowth },
  { id: "meowth1", pokemon: meowth1 },
  { id: "metapod", pokemon: metapod },
  { id: "metapod1", pokemon: metapod1 },
  { id: "mew", pokemon: mew },
  { id: "mew1", pokemon: mew1 },
  { id: "mewtwoMegax", pokemon: mewtwoMegax },
  { id: "mewtwoMegax1", pokemon: mewtwoMegax1 },
  { id: "mewtwoMegay", pokemon: mewtwoMegay },
  { id: "mewtwoMegay1", pokemon: mewtwoMegay1 },
  { id: "mewtwo", pokemon: mewtwo },
  { id: "mewtwo1", pokemon: mewtwo1 },
  { id: "moltres", pokemon: moltres },
  { id: "moltres1", pokemon: moltres1 },
  { id: "mrMime", pokemon: mrMime },
  { id: "mr_Mime", pokemon: mr_Mime },
  { id: "mr0_Mime", pokemon: mr0_Mime },
  { id: "mr1_Mime", pokemon: mr1_Mime },
  { id: "mukAlola", pokemon: mukAlola },
  { id: "mukAlola1", pokemon: mukAlola1 },
  { id: "muk", pokemon: muk },
  { id: "muk1", pokemon: muk1 },
  { id: "nidoking", pokemon: nidoking },
  { id: "nidoking1", pokemon: nidoking1 },
  { id: "nidoqueen", pokemon: nidoqueen },
  { id: "nidoqueen1", pokemon: nidoqueen1 },
  { id: "nidoran_f", pokemon: nidoran_f },
  { id: "nidoran_f1", pokemon: nidoran_f1 },
  { id: "nidoran_m", pokemon: nidoran_m },
  { id: "nidoran_m1", pokemon: nidoran_m1 },
  { id: "nidorina", pokemon: nidorina },
  { id: "nidorina1", pokemon: nidorina1 },
  { id: "nidorino", pokemon: nidorino },
  { id: "nidorino1", pokemon: nidorino1 },
  { id: "ninetalesAlola", pokemon: ninetalesAlola },
  { id: "ninetalesAlola1", pokemon: ninetalesAlola1 },
  { id: "ninetales", pokemon: ninetales },
  { id: "ninetales1", pokemon: ninetales1 },
  { id: "oddish", pokemon: oddish },
  { id: "oddish1", pokemon: oddish1 },
  { id: "omanyte", pokemon: omanyte },
  { id: "omanyte1", pokemon: omanyte1 },
  { id: "omastar", pokemon: omastar },
  { id: "omastar1", pokemon: omastar1 },
  { id: "onix", pokemon: onix },
  { id: "onix1", pokemon: onix1 },
  { id: "paras", pokemon: paras },
  { id: "paras1", pokemon: paras1 },
  { id: "parasect", pokemon: parasect },
  { id: "parasect1", pokemon: parasect1 },
  { id: "persianAlola", pokemon: persianAlola },
  { id: "persianAlola1", pokemon: persianAlola1 },
  { id: "persian", pokemon: persian },
  { id: "persian1", pokemon: persian1 },
  { id: "pidgeot", pokemon: pidgeot },
  { id: "pidgeot1", pokemon: pidgeot1 },
  { id: "pidgeotto", pokemon: pidgeotto },
  { id: "pidgeotto1", pokemon: pidgeotto1 },
  { id: "pidgey", pokemon: pidgey },
  { id: "pidgey1", pokemon: pidgey1 },
  { id: "pikachu_alolacap", pokemon: pikachu_alolacap },
  { id: "pikachu_belle", pokemon: pikachu_belle },
  { id: "pikachu_belle1", pokemon: pikachu_belle1 },
  { id: "pikachu_cosplay", pokemon: pikachu_cosplay },
  { id: "pikachu_cosplay1", pokemon: pikachu_cosplay1 },
  { id: "pikachuF", pokemon: pikachuF },
  { id: "pikachuF1", pokemon: pikachuF1 },
  { id: "pikachu_hoenncap", pokemon: pikachu_hoenncap },
  { id: "pikachu_kaloscap", pokemon: pikachu_kaloscap },
  { id: "pikachu_kantocap", pokemon: pikachu_kantocap },
  { id: "pikachu_libre", pokemon: pikachu_libre },
  { id: "pikachu_partnercap", pokemon: pikachu_partnercap },
  { id: "pikachu_phd", pokemon: pikachu_phd },
  { id: "pikachu_phd1", pokemon: pikachu_phd1 },
  { id: "pikachu_popstar", pokemon: pikachu_popstar },
  { id: "pikachu_popstar1", pokemon: pikachu_popstar1 },
  { id: "pikachu_rockstar", pokemon: pikachu_rockstar },
  { id: "pikachu_rockstar1", pokemon: pikachu_rockstar1 },
  { id: "pikachu_sinnohcap", pokemon: pikachu_sinnohcap },
  { id: "pikachu_unovacap", pokemon: pikachu_unovacap },
  { id: "pikachu", pokemon: pikachu },
  { id: "pikachu1", pokemon: pikachu1 },
  { id: "pinsirMega", pokemon: pinsirMega },
  { id: "pinsirMega1", pokemon: pinsirMega1 },
  { id: "pinsir", pokemon: pinsir },
  { id: "pinsir1", pokemon: pinsir1 },
  { id: "poliwag", pokemon: poliwag },
  { id: "poliwag1", pokemon: poliwag1 },
  { id: "poliwhirl", pokemon: poliwhirl },
  { id: "poliwhirl1", pokemon: poliwhirl1 },
  { id: "poliwrath", pokemon: poliwrath },
  { id: "poliwrath1", pokemon: poliwrath1 },
  { id: "ponyta", pokemon: ponyta },
  { id: "ponyta1", pokemon: ponyta1 },
  { id: "porygon", pokemon: porygon },
  { id: "porygon1", pokemon: porygon1 },
  { id: "primeape", pokemon: primeape },
  { id: "primeape1", pokemon: primeape1 },
  { id: "psyduck", pokemon: psyduck },
  { id: "psyduck1", pokemon: psyduck1 },
  { id: "raichuAlola", pokemon: raichuAlola },
  { id: "raichuAlola1", pokemon: raichuAlola1 },
  { id: "raichuF", pokemon: raichuF },
  { id: "raichuF1", pokemon: raichuF1 },
  { id: "raichu", pokemon: raichu },
  { id: "raichu1", pokemon: raichu1 },
  { id: "rapidash", pokemon: rapidash },
  { id: "rapidash1", pokemon: rapidash1 },
  { id: "raticateAlola", pokemon: raticateAlola },
  { id: "raticateAlola1", pokemon: raticateAlola1 },
  { id: "raticateF", pokemon: raticateF },
  { id: "raticateF1", pokemon: raticateF1 },
  { id: "raticateTotem", pokemon: raticateTotem },
  { id: "raticateTotem1", pokemon: raticateTotem1 },
  { id: "raticate", pokemon: raticate },
  { id: "raticate1", pokemon: raticate1 },
  { id: "rattataAlola", pokemon: rattataAlola },
  { id: "rattataAlola1", pokemon: rattataAlola1 },
  { id: "rattataF", pokemon: rattataF },
  { id: "rattataF1", pokemon: rattataF1 },
  { id: "rattata", pokemon: rattata },
  { id: "rattata1", pokemon: rattata1 },
  { id: "rhydonF", pokemon: rhydonF },
  { id: "rhydon", pokemon: rhydon },
  { id: "rhydon1", pokemon: rhydon1 },
  { id: "rhyhornF", pokemon: rhyhornF },
  { id: "rhyhornF1", pokemon: rhyhornF1 },
  { id: "rhyhorn", pokemon: rhyhorn },
  { id: "rhyhorn1", pokemon: rhyhorn1 },
  { id: "sandshrewAlola", pokemon: sandshrewAlola },
  { id: "sandshrewAlola1", pokemon: sandshrewAlola1 },
  { id: "sandshrew", pokemon: sandshrew },
  { id: "sandshrew1", pokemon: sandshrew1 },
  { id: "sandslashAlola", pokemon: sandslashAlola },
  { id: "sandslashAlola1", pokemon: sandslashAlola1 },
  { id: "sandslash", pokemon: sandslash },
  { id: "sandslash1", pokemon: sandslash1 },
  { id: "scytherF", pokemon: scytherF },
  { id: "scyther", pokemon: scyther },
  { id: "scyther1", pokemon: scyther1 },
  { id: "seadra", pokemon: seadra },
  { id: "seadra1", pokemon: seadra1 },
  { id: "seakingF", pokemon: seakingF },
  { id: "seakingF1", pokemon: seakingF1 },
  { id: "seaking", pokemon: seaking },
  { id: "seaking1", pokemon: seaking1 },
  { id: "seel", pokemon: seel },
  { id: "seel1", pokemon: seel1 },
  { id: "shellder", pokemon: shellder },
  { id: "shellder1", pokemon: shellder1 },
  { id: "slowbroMega", pokemon: slowbroMega },
  { id: "slowbroMega1", pokemon: slowbroMega1 },
  { id: "slowbro", pokemon: slowbro },
  { id: "slowbro1", pokemon: slowbro1 },
  { id: "slowpoke", pokemon: slowpoke },
  { id: "slowpoke1", pokemon: slowpoke1 },
  { id: "snorlax", pokemon: snorlax },
  { id: "snorlax1", pokemon: snorlax1 },
  { id: "spearow", pokemon: spearow },
  { id: "spearow1", pokemon: spearow1 },
  { id: "squirtle", pokemon: squirtle },
  { id: "squirtle1", pokemon: squirtle1 },
  { id: "starmie", pokemon: starmie },
  { id: "starmie1", pokemon: starmie1 },
  { id: "staryu", pokemon: staryu },
  { id: "staryu1", pokemon: staryu1 },
  { id: "tangela", pokemon: tangela },
  { id: "tangela1", pokemon: tangela1 },
  { id: "tauros", pokemon: tauros },
  { id: "tauros1", pokemon: tauros1 },
  { id: "tentacool", pokemon: tentacool },
  { id: "tentacool1", pokemon: tentacool1 },
  { id: "tentacruel", pokemon: tentacruel },
  { id: "tentacruel1", pokemon: tentacruel1 },
  { id: "vaporeon", pokemon: vaporeon },
  { id: "vaporeon1", pokemon: vaporeon1 },
  { id: "venomoth", pokemon: venomoth },
  { id: "venomoth1", pokemon: venomoth1 },
  { id: "venonat", pokemon: venonat },
  { id: "venonat1", pokemon: venonat1 },
  { id: "venusaurF", pokemon: venusaurF },
  { id: "venusaurF1", pokemon: venusaurF1 },
  { id: "venusaurMega", pokemon: venusaurMega },
  { id: "venusaurMega1", pokemon: venusaurMega1 },
  { id: "venusaur", pokemon: venusaur },
  { id: "venusaur1", pokemon: venusaur1 },
  { id: "victreebel", pokemon: victreebel },
  { id: "victreebel1", pokemon: victreebel1 },
  { id: "vileplumeF", pokemon: vileplumeF },
  { id: "vileplumeF1", pokemon: vileplumeF1 },
  { id: "vileplume", pokemon: vileplume },
  { id: "vileplume1", pokemon: vileplume1 },
  { id: "voltorb", pokemon: voltorb },
  { id: "voltorb1", pokemon: voltorb1 },
  { id: "vulpixAlola", pokemon: vulpixAlola },
  { id: "vulpixAlola1", pokemon: vulpixAlola1 },
  { id: "vulpix", pokemon: vulpix },
  { id: "vulpix1", pokemon: vulpix1 },
  { id: "wartortle", pokemon: wartortle },
  { id: "wartortle1", pokemon: wartortle1 },
  { id: "weedle", pokemon: weedle },
  { id: "weedle1", pokemon: weedle1 },
  { id: "weepinbell", pokemon: weepinbell },
  { id: "weepinbell1", pokemon: weepinbell1 },
  { id: "weezing", pokemon: weezing },
  { id: "weezing1", pokemon: weezing1 },
  { id: "wigglytuff", pokemon: wigglytuff },
  { id: "wigglytuff1", pokemon: wigglytuff1 },
  { id: "wigglytuF", pokemon: wigglytuF },
  { id: "wigglytuF1", pokemon: wigglytuF1 },
  { id: "zapdos", pokemon: zapdos },
  { id: "zapdos1", pokemon: zapdos1 },
  { id: "zubatF", pokemon: zubatF },
  { id: "zubatF1", pokemon: zubatF1 },
  { id: "zubat", pokemon: zubat },
  { id: "zubat1", pokemon: zubat1 },
  //gen2
  { id: "aipom_f", pokemon: aipom_f },
  { id: "aipom_f1", pokemon: aipom_f1 },
  { id: "aipom", pokemon: aipom },
  { id: "aipom1", pokemon: aipom1 },
  { id: "ampharos_mega", pokemon: ampharos_mega },
  { id: "ampharos_mega1", pokemon: ampharos_mega1 },
  { id: "ampharos", pokemon: ampharos },
  { id: "ampharos1", pokemon: ampharos1 },
  { id: "ariados", pokemon: ariados },
  { id: "ariados1", pokemon: ariados1 },
  { id: "azumarill", pokemon: azumarill },
  { id: "azumarill1", pokemon: azumarill1 },
  { id: "bayleef", pokemon: bayleef },
  { id: "bayleef1", pokemon: bayleef1 },
  { id: "bellossom", pokemon: bellossom },
  { id: "bellossom1", pokemon: bellossom1 },
  { id: "blissey", pokemon: blissey },
  { id: "blissey1", pokemon: blissey1 },
  { id: "celebi", pokemon: celebi },
  { id: "celebi1", pokemon: celebi1 },
  { id: "chikorita", pokemon: chikorita },
  { id: "chikorita1", pokemon: chikorita1 },
  { id: "chinchou", pokemon: chinchou },
  { id: "chinchou1", pokemon: chinchou1 },
  { id: "cleffa", pokemon: cleffa },
  { id: "cleffa1", pokemon: cleffa1 },
  { id: "corsola", pokemon: corsola },
  { id: "corsola1", pokemon: corsola1 },
  { id: "crobat", pokemon: crobat },
  { id: "crobat1", pokemon: crobat1 },
  { id: "croconaw", pokemon: croconaw },
  { id: "croconaw1", pokemon: croconaw1 },
  { id: "cyndaquil", pokemon: cyndaquil },
  { id: "cyndaquil1", pokemon: cyndaquil1 },
  { id: "delibird", pokemon: delibird },
  { id: "delibird1", pokemon: delibird1 },
  { id: "donphan_f", pokemon: donphan_f },
  { id: "donphan_f1", pokemon: donphan_f1 },
  { id: "donphan", pokemon: donphan },
  { id: "donphan1", pokemon: donphan1 },
  { id: "dunsparce", pokemon: dunsparce },
  { id: "dunsparce1", pokemon: dunsparce1 },
  { id: "elekid", pokemon: elekid },
  { id: "elekid1", pokemon: elekid1 },
  { id: "entei", pokemon: entei },
  { id: "entei1", pokemon: entei1 },
  { id: "espeon", pokemon: espeon },
  { id: "espeon1", pokemon: espeon1 },
  { id: "feraligatr", pokemon: feraligatr },
  { id: "feraligatr1", pokemon: feraligatr1 },
  { id: "flaaffy", pokemon: flaaffy },
  { id: "flaaffy1", pokemon: flaaffy1 },
  { id: "forretress", pokemon: forretress },
  { id: "forretress1", pokemon: forretress1 },
  { id: "furret", pokemon: furret },
  { id: "furret1", pokemon: furret1 },
  { id: "girafarig_f", pokemon: girafarig_f },
  { id: "girafarig_f1", pokemon: girafarig_f1 },
  { id: "girafarig", pokemon: girafarig },
  { id: "girafarig1", pokemon: girafarig1 },
  { id: "gligar_f", pokemon: gligar_f },
  { id: "gligar_f1", pokemon: gligar_f1 },
  { id: "gligar", pokemon: gligar },
  { id: "gligar1", pokemon: gligar1 },
  { id: "granbull", pokemon: granbull },
  { id: "granbull1", pokemon: granbull1 },
  { id: "heracross_f", pokemon: heracross_f },
  { id: "heracross_f1", pokemon: heracross_f1 },
  { id: "heracross_mega", pokemon: heracross_mega },
  { id: "heracross_mega1", pokemon: heracross_mega1 },
  { id: "heracross", pokemon: heracross },
  { id: "heracross1", pokemon: heracross1 },
  { id: "hitmontop", pokemon: hitmontop },
  { id: "hitmontop1", pokemon: hitmontop1 },
  { id: "ho-oh", pokemon: ho_oh },
  { id: "ho-oh1", pokemon: ho_oh1 },
  { id: "hoothoot", pokemon: hoothoot },
  { id: "hoothoot1", pokemon: hoothoot1 },
  { id: "hoppip", pokemon: hoppip },
  { id: "hoppip1", pokemon: hoppip1 },
  { id: "houndoom_f", pokemon: houndoom_f },
  { id: "houndoom_f1", pokemon: houndoom_f1 },
  { id: "houndoom_mega", pokemon: houndoom_mega },
  { id: "houndoom_mega1", pokemon: houndoom_mega1 },
  { id: "houndoom", pokemon: houndoom },
  { id: "houndoom1", pokemon: houndoom1 },
  { id: "houndour", pokemon: houndour },
  { id: "houndour1", pokemon: houndour1 },
  { id: "igglybuff", pokemon: igglybuff },
  { id: "igglybuff1", pokemon: igglybuff1 },
  { id: "jumpluff", pokemon: jumpluff },
  { id: "jumpluff1", pokemon: jumpluff1 },
  { id: "kingdra", pokemon: kingdra },
  { id: "kingdra1", pokemon: kingdra1 },
  { id: "lanturn", pokemon: lanturn },
  { id: "lanturn1", pokemon: lanturn1 },
  { id: "larvitar", pokemon: larvitar },
  { id: "larvitar1", pokemon: larvitar1 },
  { id: "ledian_f", pokemon: ledian_f },
  { id: "ledian_f1", pokemon: ledian_f1 },
  { id: "ledian", pokemon: ledian },
  { id: "ledian1", pokemon: ledian1 },
  { id: "ledyba_f", pokemon: ledyba_f },
  { id: "ledyba_f1", pokemon: ledyba_f1 },
  { id: "ledyba", pokemon: ledyba },
  { id: "ledyba1", pokemon: ledyba1 },
  { id: "lugia", pokemon: lugia },
  { id: "lugia1", pokemon: lugia1 },
  { id: "magby", pokemon: magby },
  { id: "magby1", pokemon: magby1 },
  { id: "magcargo", pokemon: magcargo },
  { id: "magcargo1", pokemon: magcargo1 },
  { id: "mantine", pokemon: mantine },
  { id: "mantine1", pokemon: mantine1 },
  { id: "mareep", pokemon: mareep },
  { id: "mareep1", pokemon: mareep1 },
  { id: "marill", pokemon: marill },
  { id: "marill1", pokemon: marill1 },
  { id: "meganium_f", pokemon: meganium_f },
  { id: "meganium_f1", pokemon: meganium_f1 },
  { id: "meganium", pokemon: meganium },
  { id: "meganium1", pokemon: meganium1 },
  { id: "miltank", pokemon: miltank },
  { id: "miltank1", pokemon: miltank1 },
  { id: "misdreavus", pokemon: misdreavus },
  { id: "misdreavus1", pokemon: misdreavus1 },
  { id: "murkrow_f", pokemon: murkrow_f },
  { id: "murkrow_f1", pokemon: murkrow_f1 },
  { id: "murkrow", pokemon: murkrow },
  { id: "murkrow1", pokemon: murkrow1 },
  { id: "natu", pokemon: natu },
  { id: "natu1", pokemon: natu1 },
  { id: "noctowl", pokemon: noctowl },
  { id: "noctowl1", pokemon: noctowl1 },
  { id: "octillery_f", pokemon: octillery_f },
  { id: "octillery_f1", pokemon: octillery_f1 },
  { id: "octillery", pokemon: octillery },
  { id: "octillery1", pokemon: octillery1 },
  { id: "phanpy", pokemon: phanpy },
  { id: "phanpy1", pokemon: phanpy1 },
  { id: "pichu", pokemon: pichu },
  { id: "pichu1", pokemon: pichu1 },
  { id: "piloswine_f", pokemon: piloswine_f },
  { id: "piloswine_f1", pokemon: piloswine_f1 },
  { id: "piloswine", pokemon: piloswine },
  { id: "piloswine1", pokemon: piloswine1 },
  { id: "pineco", pokemon: pineco },
  { id: "pineco1", pokemon: pineco1 },
  { id: "politoed_f", pokemon: politoed_f },
  { id: "politoed_f1", pokemon: politoed_f1 },
  { id: "politoed", pokemon: politoed },
  { id: "porygon2", pokemon: porygon2 },
  { id: "porygon21", pokemon: porygon21 },
  { id: "pupitar", pokemon: pupitar },
  { id: "pupitar1", pokemon: pupitar1 },
  { id: "quagsire_f", pokemon: quagsire_f },
  { id: "quagsire_f1", pokemon: quagsire_f1 },
  { id: "quagsire", pokemon: quagsire },
  { id: "quagsire1", pokemon: quagsire1 },
  { id: "quilava", pokemon: quilava },
  { id: "quilava1", pokemon: quilava1 },
  { id: "qwilfish", pokemon: qwilfish },
  { id: "qwilfish1", pokemon: qwilfish1 },
  { id: "raikou", pokemon: raikou },
  { id: "raikou1", pokemon: raikou1 },
  { id: "remoraid", pokemon: remoraid },
  { id: "remoraid1", pokemon: remoraid1 },
  { id: "scizor_f", pokemon: scizor_f },
  { id: "scizor_f1", pokemon: scizor_f1 },
  { id: "scizor_mega", pokemon: scizor_mega },
  { id: "scizor_mega1", pokemon: scizor_mega1 },
  { id: "scizor", pokemon: scizor },
  { id: "scizor1", pokemon: scizor1 },
  { id: "sentret", pokemon: sentret },
  { id: "sentret1", pokemon: sentret1 },
  { id: "shuckle", pokemon: shuckle },
  { id: "shuckle1", pokemon: shuckle1 },
  { id: "skarmory", pokemon: skarmory },
  { id: "skarmory1", pokemon: skarmory1 },
  { id: "skiploom", pokemon: skiploom },
  { id: "skiploom1", pokemon: skiploom1 },
  { id: "slowking", pokemon: slowking },
  { id: "slowking1", pokemon: slowking1 },
  { id: "slugma", pokemon: slugma },
  { id: "slugma1", pokemon: slugma1 },
  { id: "smeargle", pokemon: smeargle },
  { id: "smeargle1", pokemon: smeargle1 },
  { id: "smoochum", pokemon: smoochum },
  { id: "smoochum1", pokemon: smoochum1 },
  { id: "sneasel_f", pokemon: sneasel_f },
  { id: "sneasel_f1", pokemon: sneasel_f1 },
  { id: "sneasel", pokemon: sneasel },
  { id: "sneasel1", pokemon: sneasel1 },
  { id: "snubbull", pokemon: snubbull },
  { id: "snubbull1", pokemon: snubbull1 },
  { id: "spinarak", pokemon: spinarak },
  { id: "spinarak1", pokemon: spinarak1 },
  { id: "stantler", pokemon: stantler },
  { id: "stantler1", pokemon: stantler1 },
  { id: "steelix_f", pokemon: steelix_f },
  { id: "steelix_f1", pokemon: steelix_f1 },
  { id: "steelix_mega", pokemon: steelix_mega },
  { id: "steelix_mega1", pokemon: steelix_mega1 },
  { id: "steelix", pokemon: steelix },
  { id: "steelix1", pokemon: steelix1 },
  { id: "sudowoodo_f", pokemon: sudowoodo_f },
  { id: "sudowoodo_f1", pokemon: sudowoodo_f1 },
  { id: "sudowoodo", pokemon: sudowoodo },
  { id: "sudowoodo1", pokemon: sudowoodo1 },
  { id: "suicune", pokemon: suicune },
  { id: "suicune1", pokemon: suicune1 },
  { id: "sunflora", pokemon: sunflora },
  { id: "sunflora1", pokemon: sunflora1 },
  { id: "sunkern", pokemon: sunkern },
  { id: "sunkern1", pokemon: sunkern1 },
  { id: "swinub", pokemon: swinub },
  { id: "swinub1", pokemon: swinub1 },
  { id: "teddiursa", pokemon: teddiursa },
  { id: "teddiursa1", pokemon: teddiursa1 },
  { id: "togepi", pokemon: togepi },
  { id: "togepi1", pokemon: togepi1 },
  { id: "togetic", pokemon: togetic },
  { id: "togetic1", pokemon: togetic1 },
  { id: "totodile", pokemon: totodile },
  { id: "totodile1", pokemon: totodile1 },
  { id: "typhlosion", pokemon: typhlosion },
  { id: "typhlosion1", pokemon: typhlosion1 },
  { id: "tyranitar_mega", pokemon: tyranitar_mega },
  { id: "tyranitar_mega1", pokemon: tyranitar_mega1 },
  { id: "tyranitar", pokemon: tyranitar },
  { id: "tyranitar1", pokemon: tyranitar1 },
  { id: "tyrogue", pokemon: tyrogue },
  { id: "tyrogue1", pokemon: tyrogue1 },
  { id: "umbreon", pokemon: umbreon },
  { id: "umbreon1", pokemon: umbreon1 },
  { id: "unown_bravo", pokemon: unown_bravo },
  { id: "unown_bravo1", pokemon: unown_bravo1 },
  { id: "unown_charlie", pokemon: unown_charlie },
  { id: "unown_charlie1", pokemon: unown_charlie1 },
  { id: "unown_delta", pokemon: unown_delta },
  { id: "unown_delta1", pokemon: unown_delta1 },
  { id: "unown_echo", pokemon: unown_echo },
  { id: "unown_echo1", pokemon: unown_echo1 },
  { id: "unown_exclamation", pokemon: unown_exclamation },
  { id: "unown_exclamation1", pokemon: unown_exclamation1 },
  { id: "unown_foxtrot", pokemon: unown_foxtrot },
  { id: "unown_foxtrot1", pokemon: unown_foxtrot1 },
  { id: "unown_golf", pokemon: unown_golf },
  { id: "unown_golf1", pokemon: unown_golf1 },
  { id: "unown_hotel", pokemon: unown_hotel },
  { id: "unown_hotel1", pokemon: unown_hotel1 },
  { id: "unown_india", pokemon: unown_india },
  { id: "unown_india1", pokemon: unown_india1 },
  { id: "unown_interrogation", pokemon: unown_interrogation },
  { id: "unown_interrogation1", pokemon: unown_interrogation1 },
  { id: "unown_juliet", pokemon: unown_juliet },
  { id: "unown_juliet1", pokemon: unown_juliet1 },
  { id: "unown_kilo", pokemon: unown_kilo },
  { id: "unown_kilo1", pokemon: unown_kilo1 },
  { id: "unown_lima", pokemon: unown_lima },
  { id: "unown_lima1", pokemon: unown_lima1 },
  { id: "unown_mike", pokemon: unown_mike },
  { id: "unown_mike1", pokemon: unown_mike1 },
  { id: "unown_november", pokemon: unown_november },
  { id: "unown_november1", pokemon: unown_november1 },
  { id: "unown_oscar", pokemon: unown_oscar },
  { id: "unown_oscar1", pokemon: unown_oscar1 },
  { id: "unown_papa", pokemon: unown_papa },
  { id: "unown_papa1", pokemon: unown_papa1 },
  { id: "unown_quebec", pokemon: unown_quebec },
  { id: "unown_quebec1", pokemon: unown_quebec1 },
  { id: "unown_romeo", pokemon: unown_romeo },
  { id: "unown_romeo1", pokemon: unown_romeo1 },
  { id: "unown_sierra", pokemon: unown_sierra },
  { id: "unown_sierra1", pokemon: unown_sierra1 },
  { id: "unown_tango", pokemon: unown_tango },
  { id: "unown_tango1", pokemon: unown_tango1 },
  { id: "unown_uniform", pokemon: unown_uniform },
  { id: "unown_uniform1", pokemon: unown_uniform1 },
  { id: "unown_victor", pokemon: unown_victor },
  { id: "unown_victor1", pokemon: unown_victor1 },
  { id: "unown_whiskey", pokemon: unown_whiskey },
  { id: "unown_whiskey1", pokemon: unown_whiskey1 },
  { id: "unown_xray", pokemon: unown_xray },
  { id: "unown_xray1", pokemon: unown_xray1 },
  { id: "unown_yankee", pokemon: unown_yankee },
  { id: "unown_yankee1", pokemon: unown_yankee1 },
  { id: "unown_zulu", pokemon: unown_zulu },
  { id: "unown_zulu1", pokemon: unown_zulu1 },
  { id: "unown", pokemon: unown },
  { id: "unown1", pokemon: unown1 },
  { id: "ursaring_f", pokemon: ursaring_f },
  { id: "ursaring_f1", pokemon: ursaring_f1 },
  { id: "ursaring", pokemon: ursaring },
  { id: "ursaring1", pokemon: ursaring1 },
  { id: "wobbuffet_f", pokemon: wobbuffet_f },
  { id: "wobbuffet_f1", pokemon: wobbuffet_f1 },
  { id: "wobbuffet", pokemon: wobbuffet },
  { id: "wobbuffet1", pokemon: wobbuffet1 },
  { id: "wooper_f", pokemon: wooper_f },
  { id: "wooper_f1", pokemon: wooper_f1 },
  { id: "wooper", pokemon: wooper },
  { id: "wooper1", pokemon: wooper1 },
  { id: "xatu_f", pokemon: xatu_f },
  { id: "xatu_f1", pokemon: xatu_f1 },
  { id: "xatu", pokemon: xatu },
  { id: "xatu1", pokemon: xatu1 },
  { id: "yanma", pokemon: yanma },
  { id: "yanma1", pokemon: yanma1 },
];
//let randomize = Math.floor(Math.random() * pokemonAssetArr.length);

const PokemonAsset = ({ pokemonLoaded }) => {
  console.log("pokemonLoaded val", pokemonLoaded);
  let foundObj = pokemonAssetArr.find((i) => {
    return pokemonLoaded === "nidoran-f"
      ? i.id === "nidoran_f"
      : pokemonLoaded === "nidoran-m"
      ? i.id === "nidoran_m"
      : pokemonLoaded === "mr-mime"
      ? i.id === "mrMime"
      : i.id === pokemonLoaded;
  });

  return (
    <img
      alt="pokemon"
      src={foundObj.pokemon}
      style={{ maxHeight: 150, height: 100 }}
    />
  );
};
//

export default PokemonAsset;
